CHISEL_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
CHISEL_OUT_DIR := $(abspath $(CHISEL_DIR)/..)

CHISEL_MAIN_ALU := ALUMain
CHISEL_MAIN_CPU := cpu.Main
CHISEL_MAIN_CSR := csr.Main
CHISEL_MAIN_DMEM := DMEMMain
CHISEL_MAIN_GPR := GPRMain
CHISEL_MAIN_IDU := IDUMain
CHISEL_MAIN_IFU := IFUMain
CHISEL_MAIN_IMEM := IMEMMain
CHISEL_MAIN_LSU := LSUMain
CHISEL_MAIN_WBU := WBUMain

CHISEL_EMITTED_ALU := ALU.sv
CHISEL_EMITTED_CPU := CPU.sv
CHISEL_EMITTED_CSR := CSRctl.sv
CHISEL_EMITTED_DMEM := DMEM_d.sv
CHISEL_EMITTED_GPR := GPR.sv
CHISEL_EMITTED_IDU := IDU.sv
CHISEL_EMITTED_IFU := IFU.sv
CHISEL_EMITTED_IMEM := IMEM_d.sv
CHISEL_EMITTED_LSU := LSU.sv
CHISEL_EMITTED_WBU := WBU.sv

CHISEL_MAIN := $(CHISEL_MAIN_$(TOP))
CHISEL_EMITTED := $(CHISEL_EMITTED_$(TOP))

.PHONY: genv
genv:
	cd $(CHISEL_DIR) && mill -i $(TOP).runMain $(CHISEL_MAIN)
	@echo "Generated $(CHISEL_OUT_DIR)/$(CHISEL_EMITTED)"
